"""
StreetRod3 .mat text format writer.

Syntax understood by CModel::loadMaterials / CMaterial::Load:

    MaterialName {
        Pass1 {
            Texture   FILENAME.PNG
            RGB       r,g,b          -- base colour (0.0-1.0 each)
            Alpha     0.75           -- opacity
            Blend     b_alpha        -- blending keyword
            TcGen     tc_sphere      -- UV generation (chrome/mirror effect)
            backcull  false          -- back-face culling
            lighting  true
        }
        Pass2 { ... }               -- up to MAX_PASSES passes
    }

Notes:
  - Material names in this file are matched (case-insensitive) against the
    names embedded in the companion .aux file.
  - 'CarMaterial' is detected by CCar::LoadModel to read the paint colour.
  - 'window' is the conventional name for semi-transparent glass.
"""

import bpy
import os


# ---------------------------------------------------------------------------
# Blender material inspection helpers
# ---------------------------------------------------------------------------

def _get_image_texture_filename(bl_mat) -> str | None:
    """Return the base filename of the first Image Texture node, or None."""
    if bl_mat is None or not bl_mat.use_nodes:
        return None
    for node in bl_mat.node_tree.nodes:
        if node.type == 'TEX_IMAGE' and node.image:
            raw = node.image.filepath or (node.image.name + '.png')
            return os.path.basename(raw)
    return None


def _get_base_colour(bl_mat) -> tuple:
    """Return (R, G, B) base colour from the Principled BSDF, or white."""
    if bl_mat is None or not bl_mat.use_nodes:
        return (1.0, 1.0, 1.0)
    for node in bl_mat.node_tree.nodes:
        if node.type == 'BSDF_PRINCIPLED':
            c = node.inputs['Base Color'].default_value
            return (float(c[0]), float(c[1]), float(c[2]))
    return (1.0, 1.0, 1.0)


def _get_alpha(bl_mat) -> float:
    """Return the alpha value from the Principled BSDF Alpha input."""
    if bl_mat is None or not bl_mat.use_nodes:
        return 1.0
    for node in bl_mat.node_tree.nodes:
        if node.type == 'BSDF_PRINCIPLED':
            return float(node.inputs['Alpha'].default_value)
    return 1.0


def _is_transparent(bl_mat) -> bool:
    """True if the material uses alpha blending in Blender."""
    if bl_mat is None:
        return False
    return bl_mat.blend_method in ('BLEND', 'HASHED', 'CLIP')


# ---------------------------------------------------------------------------
# Main writer
# ---------------------------------------------------------------------------

def write_mat(filepath: str, model) -> None:
    """Write a .mat file for all materials listed in *model.material_names*.

    Each Blender material is looked up by name in bpy.data.materials.
    Unknown materials get sensible defaults.
    """
    # Build name → Blender material lookup
    bl_mats = {m.name: m for m in bpy.data.materials
               if m.name in model.material_names}

    with open(filepath, 'wt', encoding='ascii', errors='replace') as fp:
        fp.write('# StreetRod3 material file\n')
        fp.write('# Generated by SR3 AUX Exporter for Blender\n\n')

        for mat_name in model.material_names:
            bl_mat = bl_mats.get(mat_name)
            name_lower = mat_name.lower()

            tex_file  = _get_image_texture_filename(bl_mat)
            r, g, b   = _get_base_colour(bl_mat)
            alpha     = _get_alpha(bl_mat)
            is_transp = _is_transparent(bl_mat) or name_lower == 'window'
            is_car    = (mat_name == 'CarMaterial')

            fp.write(f'{mat_name} {{\n')

            # ------ Pass 1 ------------------------------------------------
            fp.write('\tPass1 {\n')

            if is_car:
                # Car paint: environment map in pass 1, tinted overlay in pass 2
                if tex_file:
                    fp.write(f'\t\tTexture {tex_file}\n')
                fp.write('\t\tTcGen tc_sphere\n')
            elif tex_file:
                fp.write(f'\t\tTexture {tex_file}\n')
            else:
                fp.write(f'\t\tRGB {r:.6f},{g:.6f},{b:.6f}\n')

            if is_transp:
                fp.write(f'\t\tAlpha {alpha:.3f}\n')
                fp.write('\t\tBlend b_alpha\n')
                fp.write('\t\tbackcull false\n')

            fp.write('\t}\n')

            # ------ Pass 2 (CarMaterial only) -----------------------------
            if is_car:
                fp.write('\tPass2 {\n')
                fp.write(f'\t\tRGB {r:.6f},{g:.6f},{b:.6f}\n')
                fp.write(f'\t\tAlpha {alpha:.3f}\n')
                fp.write('\t\tBlend b_alpha\n')
                fp.write('\t\tbackcull false\n')
                fp.write('\t}\n')

            fp.write('}\n\n')
